os: Visual Studio 2015

platform: x64

configuration: Release

environment:
    MINICONDA_ROOT: C:\Miniconda36-x64
    NSIS_ROOT: C:\Program Files (x86)\NSIS
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
 
install:
  - git submodule update --init --recursive

  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - ps: choco install -y -r swig --version 3.0.9
  - ps: choco install -y -r sqlite --version 3.19.2
  - ps: choco install -y -r pkgconfiglite # TODO can we get rid of this dependency?
  
  - ps: Start-FileDownload 'https://github.com/seweber/pairinteraction-build-dependencies/releases/download/v110/cpp-libraries-windows-x86_64.zip'
  - cmd: 7z x -y cpp-libraries-windows-x86_64.zip > nul

  - ps: Start-FileDownload 'https://github.com/seweber/pairinteraction-build-dependencies/releases/download/v110/python-packages-windows_x86_64.zip'
  - cmd: 7z x -y python-packages-windows_x86_64.zip > nul
  - cmd: call %MINICONDA_ROOT%\Scripts\activate.bat
  - cmd: conda config --prepend channels file:///%APPVEYOR_BUILD_FOLDER%/conda-export
  - cmd: conda install -y -q pairinteraction-dependencies
  - cmd: pip install git+https://github.com/pyinstaller/pyinstaller # TODO if new version that supports python 3.6 in conda-forge, specify version of pyinstaller and include pyinstaller in conda-export 
 
cache:
  - C:\ProgramData\chocolatey\bin -> .appveyor.yml
  - C:\ProgramData\chocolatey\lib -> .appveyor.yml

before_build:
  - cmd: ls "C:/projects/pairinteraction" 
  - cmd: md build && cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" .. -DWITH_DOCS=no -DCMAKE_TOOLCHAIN_FILE=vcpkg-export\scripts\buildsystems\vcpkg.cmake"

build:
  project: build\pairinteraction.sln
  parallel: true
  verbosity: minimal

after_build:
  #- cmd: pyinstaller gui\startgui
  - cmd: ls "C:/projects/pairinteraction/build/win32"
  - cmd: cd .. 
  - cmd: dir
  - cmd: ls win32
  - cmd: pyinstaller win32\startgui.spec
  - cmd: ls "C:/projects/pairinteraction/build"
  - cmd: more startgui.spec  
  - cmd: copy "C:\Program Files\Microsoft SDKs\Windows\v7.1\Redist\VC\vcredist_x64.exe" calc\
  - cmd: 7z a -tzip pairinteraction-install-windows-x86_64.zip calc > nul

artifacts:
  - path: build\pairinteraction-install-windows-x86_64.zip
    name: installer

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(GH_TOKEN)
    artifact:  installer
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true  
